openapi: "3.0.3"
info:
  title: "TvHistoryApi"
  summary: "Управление каналами и списком телепередачь"
  version: "1.0.0"
servers:
  - url: "http://176.109.106.211:8080"
  - url: "http://127.0.0.1:8080"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, for documentation purposes only

paths:
  /api/auth/register:
    post:
      summary: "Регистрация нового пользователя"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "OK"


  /api/auth/refresh:
    post:
      summary: "Получение новго access токена"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string

      responses:
        "200":
          description: "OK"

  /api/auth/login:
    post:
      summary: "Вход по логину и паролю"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "OK"

  /api/users/{id}:
    get:
      summary: "Получение неполной информации о пользователе"
      parameters:
        - name: "id"
          required: true
          in: path

      responses:
        "200":
          description: "OK"

  /api/users/@me:
    get:
      summary: "Получение полной информации о пользователе"
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: "OK"

  /api/users/{id}/avatar:
    get:
      summary: "Получение автара"
      parameters:
        - name: "id"
          required: true
          in: path
      responses:
        "200":
          description: "OK"

  /api/users/@me/avatar:
    get:
      security:
        - bearerAuth: [ ]
      summary: "Получение автара"

      responses:
        "200":
          description: "OK"
    post:
      summary: "Установка автара"
      security:
        - bearerAuth: [ ]
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
      requestBody:
        content:
          image/jpeg:
            schema:
              # a binary file of any type
              type: string
              format: binary

          image/png:
            schema:
              # a binary file of any type
              type: string
              format: binary

      responses:
        "200":
          description: "OK"

  /api/channels:
    get:
      summary: "Получить список каналов"
      parameters:
        - name: "limit"
          required: false
          in: query

        - name: "offset"
          required: false
          in: query

        - name: "name"
          required: false
          in: query

      responses:
        "200":
          description: "OK"
#          content:
#            text/json:
#              schema:
#                type: object
#                properties:
#                  leftAmount:
#                    type: integer
#                    example: 512
#                  channels:
#                    type: array
#                    example: [
#                      {
#                        id: 123,
#                        name: "Первый канал",
#                        image: "https:...",
#                      }
#                    ]


  /api/channels/{id}:
    get:
      summary: "Получение подробностей о канале"
      parameters:
        - name: "id"
          required: true
          in: path
      responses:
        "200":
          description: "OK"
#          content:
#            text/json:
#              schema:
#                type: "object"
#                properties:
#                  id:
#                    type: integer
#                    example: 123
#                  name:
#                    type: string
#                    example: "Первый канал"
#                  image:
#                    type: string
#                    example: "https:..."
#                  summary:
#                    type: string
#                    example: "https:..."
#                  view_urls:
#                        type: array
#                        example: [
#                          "https:...",
#                          "https:...",
#                          "https:...",
#                          "https:..."
#                        ]

  /api/channels/{id}/releases:
    get:
      summary: "Получение списка выпусков телепередачь на канале"
      parameters:
        - name: "id"
          required: true
          in: path

        - name: "limit"
          required: false
          in: query

        - name: "time-start"
          required: false
          in: query

        - name: "time-zone"
          required: false
          in: query
      responses:
        "200":
          description: "OK"
#          content:
#            text/json:
#              schema:
#                type: "object"
#                properties:
#                  timeSpanCount:
#                    type: integer
#                    example: 4
#                  timeStart:
#                    type: integer
#                    example: 1719059700
#                  timeEnd:
#                    type: integer
#                    example: 1719069700
#                  shows:
#                    type: array
#                    example: [
#                        {
#                          id: 123,
#                          name: "Они сражались за Родину",
#                          assessment: 4.6,
#                          age-limit: 0,
#                          previewImage: "https://....",
#                          dates: [
#                            {
#                              timeStart: 1719059700,
#                              timeEnd: 1719068400
#                            },
#                            {
#                              timeStart: 1719059700,
#                              timeEnd: 1719068400
#                            }
#                          ]
#                        },
#                        {
#                          id: 321,
#                          name: "Кухня",
#                          assessment: 4.6,
#                          age-limit: 0,
#                          previewImage: "https://....",
#                          dates: [
#                            {
#                              timeStart: 1719059700,
#                              timeEnd: 1719068400
#                            },
#                            {
#                              timeStart: 1719059700,
#                              timeEnd: 1719068400
#                            }
#                          ]
#                        }
#                      ]
  /api/shows:
    get:
      summary: "Получение списка телепередачь"
      parameters:
        - name: "limit"
          required: false
          in: query

        - name: "offset"
          required: false
          in: query

        - name: "name"
          required: false
          in: query
      responses:
        "200":
          description: "OK"

  /api/shows/{id}:
    get:
      summary: "Получение подробностей о телепередаче"
      parameters:
        - name: "id"
          required: false
          in: path
      responses:
        "200":
          description: "OK"
#          content:
#            text/json:
#              schema:
#                type: "object"
#                properties:
#                  id:
#                    type: integer
#                    example: 123
#                  name:
#                    type: string
#                    example: "Кухня"
#                  assessment:
#                    type: number
#                    example: 4.6
#                  ageLimit:
#                      type: number
#                      example: 0
#                      summary: "
#                        0 - наш сибирский (как пример 0+ (0b0000) 6+ (0b0001) 12+ (0b0010) 18+ (0b0011))\n
#                        1 - их пендоский (G (0b1000) PG (0b1001) PG-13 (0b1010) R (0b1011) NC-17 (0b1100))
#                      "
#
#                  previewImage:
#                    type: string
#                    example: "https:..."
#                  summary:
#                    type: string
#                    example: "1-й сезон. На кухне модного московского ресторана «Клод Моне» появляется новый повар — Максим Лавров.
#                      2-й сезон. Отношения Макса и Вики заходят в тупик. Этому способствует сближение Макса и официантки Саши.
#                      3-й сезон. Макс начинает свою работу в качестве официанта.
#                      5-й сезон. Команде Виктора Баринова придётся уйти работать в другой ресторан.
#                      6-й сезон. В заключительном шестом сезоне шеф принимает судьбоносное решение, выбирая между жизнью и смертью."

  /api/shows/{id}/channels:
    get:
      summary: "Получение списка телепередачь на канале"
      parameters:
        - name: "id"
          required: true
          in: path

        - name: "channels-limit"
          required: false
          in: "query"

        - name: "channels-offset"
          required: false
          in: "query"

        - name: "releases-limit"
          required: false
          in: "query"

        - name: "releases-start"
          required: false
          in: "query"

        - name: "time-zone"
          required: false
          in: "query"


      responses:
        "200":
          description: "OK"
#          content:
#            text/json:
#              schema:
#                type: "object"
#                properties:
#                  channels:
#                    type: array
#                    example: [
#                        {
#                          id: 123,
#                          name: "Первый канал",
#                          image: "https:...",
#                          dates: [
#                            {
#                              timeStart: 1719059700,
#                              stopTime: 1719068400
#                            },
#                            {
#                              timeStart: 1719059700,
#                              stopTime: 1719068400
#                            }
#                          ]
#                        }
#                      ]

  /api/shows/favorites:
    get:
      summary: "Получение списка избранных шоу"
      parameters:
        - name: "limit"
          required: false
          in: query
        - name: "offset"
          required: false
          in: query

      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: "OK"

    post:
      summary: "Добавление в избранное"
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
      responses:
        "200":
          description: "OK"
    delete:
      summary: "Удаление из избранного"
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
      responses:
        "200":
          description: "OK"


  /api/shows/{id}/reviews:
    get:
      summary: "Получение списка отзывов"
      parameters:
        - name: "id"
          required: true
          in: path
        - name: "limit"
          required: false
          in: query
        - name: "time-start"
          in: query
          required: false
        - name: "time-zone"
          in: query
          required: false
        - name: "assessment"
          in: query
          required: false

      responses:
        "200":
          description: "OK"
    post:
      summary: "Добавление или изменение (если существует) отзыва"
      security:
        - bearerAuth: [ ]
      parameters:
        - name: "id"
          required: true
          in: path
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assessment:
                  type: number
                text:
                  type: string
      responses:
        "200":
          description: "OK"

  /api/shows/{id}/distribution:
    get:
      summary: "Получение количества оценок"
      parameters:
        - name: "id"
          required: true
          in: path

      responses:
        "200":
          description: "OK"

  /api/shows/{id}/reviews/@my:
    get:
      summary: "Получение отзыва пользователя"
      security:
        - bearerAuth: [ ]
      parameters:
        - name: "id"
          required: true
          in: path
      responses:
        "200":
          description: "OK"
    delete:
      summary: "Удаление отзыва"
      parameters:
        - name: "id"
          required: true
          in: path
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: "OK"


  /api/channels/favorites:
    get:
      summary: "Получение списка избранных шоу"
      parameters:
        - name: "limit"
          required: false
          in: query
        - name: "offset"
          required: false
          in: query
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: "OK"

    post:
      summary: "Добавление в избранное"
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
      responses:
        "200":
          description: "OK"
    delete:
      summary: "Удаление из избранного"
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
      responses:
        "200":
          description: "OK"

  /api/channels/{id}/reviews:
    get:
      summary: "Получение списка отзывов"
      parameters:
        - name: "id"
          required: true
          in: path
        - name: "limit"
          required: false
          in: query
        - name: "time-start"
          in: query
          required: false
        - name: "time-zone"
          in: query
          required: false
        - name: "assessment"
          in: query
          required: false
      responses:
        "200":
          description: "OK"
    post:
      summary: "Добавление или изменение (если существует) отзыва"
      security:
        - bearerAuth: [ ]
      parameters:
        - name: "id"
          required: true
          in: path
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assessment:
                  type: number
                text:
                  type: string
      responses:
        "200":
          description: "OK"

  /api/channels/{id}/distribution:
    get:
      summary: "Получение количества оценок"
      parameters:
        - name: "id"
          required: true
          in: path

      responses:
        "200":
          description: "OK"

  /api/channels/{id}/reviews/@my:
    get:
      summary: "Получение отзыва пользователя"
      security:
        - bearerAuth: [ ]
      parameters:
        - name: "id"
          required: true
          in: path
      responses:
        "200":
          description: "OK"
    delete:
      summary: "Удаление отзыва"
      parameters:
        - name: "id"
          required: true
          in: path
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "OK"
