openapi: "3.0.3"
info:
  title: "TvHistoryApi"
  description: "Управление каналами и списком телепередачь"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080"
  - url: "http://176.109.106.211:8080"

paths:
  /api/channels:
    get:
      description: "Получить список каналов"
      parameters:
        - name: "limit"
          required: false
          in: query

        - name: "offset"
          required: false
          in: query

        - name: "name"
          required: false
          in: query

      responses:
        "200":
          description: "OK"
#          content:
#            text/json:
#              schema:
#                type: object
#                properties:
#                  leftAmount:
#                    type: integer
#                    example: 512
#                  channels:
#                    type: array
#                    example: [
#                      {
#                        id: 123,
#                        name: "Первый канал",
#                        image: "https:...",
#                      }
#                    ]


  /api/channels/{id}:
    get:
      description: "Получение подробностей о канале"
      parameters:
        - name: "id"
          required: true
          in: path
      responses:
        "200":
          description: "OK"
#          content:
#            text/json:
#              schema:
#                type: "object"
#                properties:
#                  id:
#                    type: integer
#                    example: 123
#                  name:
#                    type: string
#                    example: "Первый канал"
#                  image:
#                    type: string
#                    example: "https:..."
#                  description:
#                    type: string
#                    example: "https:..."
#                  view_urls:
#                        type: array
#                        example: [
#                          "https:...",
#                          "https:...",
#                          "https:...",
#                          "https:..."
#                        ]

  /api/channels/{id}/releases:
    get:
      description: "Получение списка выпусков телепередачь на канале"
      parameters:
        - name: "id"
          required: true
          in: path

        - name: "limit"
          required: false
          in: query

        - name: "time-start"
          required: false
          in: query

        - name: "time-zone"
          required: false
          in: query
      responses:
        "200":
          description: "OK"
#          content:
#            text/json:
#              schema:
#                type: "object"
#                properties:
#                  timeSpanCount:
#                    type: integer
#                    example: 4
#                  timeStart:
#                    type: integer
#                    example: 1719059700
#                  timeEnd:
#                    type: integer
#                    example: 1719069700
#                  shows:
#                    type: array
#                    example: [
#                        {
#                          id: 123,
#                          name: "Они сражались за Родину",
#                          assessment: 4.6,
#                          age-limit: 0,
#                          previewImage: "https://....",
#                          dates: [
#                            {
#                              timeStart: 1719059700,
#                              timeEnd: 1719068400
#                            },
#                            {
#                              timeStart: 1719059700,
#                              timeEnd: 1719068400
#                            }
#                          ]
#                        },
#                        {
#                          id: 321,
#                          name: "Кухня",
#                          assessment: 4.6,
#                          age-limit: 0,
#                          previewImage: "https://....",
#                          dates: [
#                            {
#                              timeStart: 1719059700,
#                              timeEnd: 1719068400
#                            },
#                            {
#                              timeStart: 1719059700,
#                              timeEnd: 1719068400
#                            }
#                          ]
#                        }
#                      ]
  /api/shows:
    get:
      description: "Получение списка телепередачь"
      parameters:
        - name: "limit"
          required: false
          in: query

        - name: "offset"
          required: false
          in: query

        - name: "name"
          required: false
          in: query
      responses:
        "200":
          description: "OK"

  /api/shows/{id}:
    get:
      description: "Получение подробностей о телепередаче"
      parameters:
        - name: "id"
          required: false
          in: path
      responses:
        "200":
          description: "OK"
#          content:
#            text/json:
#              schema:
#                type: "object"
#                properties:
#                  id:
#                    type: integer
#                    example: 123
#                  name:
#                    type: string
#                    example: "Кухня"
#                  assessment:
#                    type: number
#                    example: 4.6
#                  ageLimit:
#                      type: number
#                      example: 0
#                      description: "
#                        0 - наш сибирский (как пример 0+ (0b0000) 6+ (0b0001) 12+ (0b0010) 18+ (0b0011))\n
#                        1 - их пендоский (G (0b1000) PG (0b1001) PG-13 (0b1010) R (0b1011) NC-17 (0b1100))
#                      "
#
#                  previewImage:
#                    type: string
#                    example: "https:..."
#                  description:
#                    type: string
#                    example: "1-й сезон. На кухне модного московского ресторана «Клод Моне» появляется новый повар — Максим Лавров.
#                      2-й сезон. Отношения Макса и Вики заходят в тупик. Этому способствует сближение Макса и официантки Саши.
#                      3-й сезон. Макс начинает свою работу в качестве официанта.
#                      5-й сезон. Команде Виктора Баринова придётся уйти работать в другой ресторан.
#                      6-й сезон. В заключительном шестом сезоне шеф принимает судьбоносное решение, выбирая между жизнью и смертью."

  /api/shows/{id}/channels:
    get:
      description: "Получение списка телепередачь на канале"
      parameters:
        - name: "id"
          required: true
          in: path

        - name: "channels-limit"
          required: false
          in: "query"

        - name: "channels-offset"
          required: false
          in: "query"

        - name: "releases-limit"
          required: false
          in: "query"

        - name: "releases-start"
          required: false
          in: "query"

        - name: "time-zone"
          required: false
          in: "query"


      responses:
        "200":
          description: "OK"
#          content:
#            text/json:
#              schema:
#                type: "object"
#                properties:
#                  channels:
#                    type: array
#                    example: [
#                        {
#                          id: 123,
#                          name: "Первый канал",
#                          image: "https:...",
#                          dates: [
#                            {
#                              timeStart: 1719059700,
#                              stopTime: 1719068400
#                            },
#                            {
#                              timeStart: 1719059700,
#                              stopTime: 1719068400
#                            }
#                          ]
#                        }
#                      ]

components:
  schemas: { }