GET http://127.0.0.1:8080/api/channels
method: GET
Accept:application/json

###
GET http://127.0.0.1:8080/api/channels/15569
method: GET
Accept:application/json

###
GET http://127.0.0.1:8080/api/channels/15569/releases
method: GET
Accept:application/json


###
GET http://127.0.0.1:8080/api/shows
method: GET
Accept:application/json

###
GET http://127.0.0.1:8080/api/shows/1013351
method: GET
Accept:application/json

###
GET http://127.0.0.1:8080/api/shows/1013351/channels
method: GET
Accept:application/json